[project]
name = "py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flash-attn>=2.8.3",
    "protobuf>=6.32.0",
    "sentencepiece>=0.2.1",
    "torch>=2.8.0",
    "transformers>=4.55.2",
]
